version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf build dist

  install:
    cmds:
      - pnpm install
      - pnpm prune

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm build

  test:
    desc: Test
    deps: [ install ]
    cmds:
      - pnpm run test
